const { create } = require('xmlbuilder2');

/**
 * Generate Torznab capabilities XML
 *
 * This endpoint declares what search types and categories the indexer supports.
 * Sonarr/Radarr query this to understand how to interact with the indexer.
 *
 * @returns {string} XML capabilities response
 */
function generateCapabilities() {
  const root = create({ version: '1.0', encoding: 'UTF-8' })
    .ele('caps')
      .ele('server')
        .att('version', '1.0')
        .att('title', 'aMule ED2K Indexer')
      .up()
      .ele('limits')
        .att('max', '100')
        .att('default', '100')
      .up()
      .ele('searching')
        .ele('search')
          .att('available', 'yes')
          .att('supportedParams', 'q')
        .up()
        .ele('tv-search')
          .att('available', 'yes')
          .att('supportedParams', 'q,season,ep')
        .up()
        .ele('movie-search')
          .att('available', 'yes')
          .att('supportedParams', 'q')
        .up()
        .ele('audio-search')
          .att('available', 'yes')
          .att('supportedParams', 'q,artist,album')
        .up()
      .up()
      .ele('categories')
        .ele('category')
          .att('id', '2000')
          .att('name', 'Movies')
          .ele('subcat')
            .att('id', '2010')
            .att('name', 'Movies/Foreign')
          .up()
          .ele('subcat')
            .att('id', '2020')
            .att('name', 'Movies/Other')
          .up()
          .ele('subcat')
            .att('id', '2030')
            .att('name', 'Movies/SD')
          .up()
          .ele('subcat')
            .att('id', '2040')
            .att('name', 'Movies/HD')
          .up()
          .ele('subcat')
            .att('id', '2045')
            .att('name', 'Movies/UHD')
          .up()
          .ele('subcat')
            .att('id', '2050')
            .att('name', 'Movies/BluRay')
          .up()
          .ele('subcat')
            .att('id', '2060')
            .att('name', 'Movies/3D')
          .up()
          .ele('subcat')
            .att('id', '2070')
            .att('name', 'Movies/DVD')
          .up()
          .ele('subcat')
            .att('id', '2080')
            .att('name', 'Movies/WEB-DL')
          .up()
          .ele('subcat')
            .att('id', '2090')
            .att('name', 'Movies/x265')
          .up()
        .up()
        .ele('category')
          .att('id', '3000')
          .att('name', 'Audio')
          .ele('subcat')
            .att('id', '3010')
            .att('name', 'Audio/MP3')
          .up()
          .ele('subcat')
            .att('id', '3020')
            .att('name', 'Audio/Video')
          .up()
          .ele('subcat')
            .att('id', '3030')
            .att('name', 'Audio/Audiobook')
          .up()
          .ele('subcat')
            .att('id', '3040')
            .att('name', 'Audio/Lossless')
          .up()
          .ele('subcat')
            .att('id', '3050')
            .att('name', 'Audio/Other')
          .up()
          .ele('subcat')
            .att('id', '3060')
            .att('name', 'Audio/Foreign')
          .up()
        .up()
        .ele('category')
          .att('id', '5000')
          .att('name', 'TV')
          .ele('subcat')
            .att('id', '5010')
            .att('name', 'TV/WEB-DL')
          .up()
          .ele('subcat')
            .att('id', '5020')
            .att('name', 'TV/Foreign')
          .up()
          .ele('subcat')
            .att('id', '5030')
            .att('name', 'TV/SD')
          .up()
          .ele('subcat')
            .att('id', '5040')
            .att('name', 'TV/HD')
          .up()
          .ele('subcat')
            .att('id', '5045')
            .att('name', 'TV/UHD')
          .up()
          .ele('subcat')
            .att('id', '5050')
            .att('name', 'TV/Other')
          .up()
          .ele('subcat')
            .att('id', '5060')
            .att('name', 'TV/Sport')
          .up()
          .ele('subcat')
            .att('id', '5070')
            .att('name', 'TV/Anime')
          .up()
          .ele('subcat')
            .att('id', '5080')
            .att('name', 'TV/Documentary')
          .up()
          .ele('subcat')
            .att('id', '5090')
            .att('name', 'TV/x265')
          .up()
        .up()
      .up()
    .up();

  return root.end({ prettyPrint: true });
}

module.exports = { generateCapabilities };
